name: MSBuild
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
    - uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[15.8, 15.9)'
    - name: Pack
      run: |
        vcpkg install xlnt:x64-windows
        vcpkg export xlnt:x64-windows --zip
    - uses: actions/upload-artifact@v2
      with:
        name: Upload
        path: C:/vcpkg/*.zip
