name: MSBuild
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.5.0
      with:
        toolset: 15.XX 
#     - name: Pack
#       run: |
#         vcpkg install xlnt:x64-windows
#         vcpkg export xlnt:x64-windows --zip
#     - uses: actions/upload-artifact@v2
#       with:
#         name: Upload
#         path: C:/vcpkg/*.zip
